apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- nginx-configmap.yaml
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: yamlamadingdong
  spec:
    template:
      spec:
        containers:
          - name: yamlamadingdong
            imagePullPolicy: IfNotPresent
          - name: auto-ssl
            imagePullPolicy: IfNotPresent

resources:
- ../../base
