---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-top
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/app-top
  uid: 8101baa7-be4c-11e9-a9e7-42010a8001ba
  resourceVersion: '149200316'
  generation: 1
  creationTimestamp: '2019-08-14T04:32:20Z'
  labels:
    app.kubernetes.io/managed-by: skaffold-v0.35.0
    role: app-top
    skaffold.dev/builder: google-cloud-build
    skaffold.dev/cleanup: 'true'
    skaffold.dev/deployer: kustomize
    skaffold.dev/tag-policy: envTemplateTagger
    skaffold.dev/tail: 'true'
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/managed-by":"skaffold-v0.35.0","role":"app-top","skaffold.dev/builder":"google-cloud-build","skaffold.dev/cleanup":"true","skaffold.dev/deployer":"kustomize","skaffold.dev/tag-policy":"envTemplateTagger","skaffold.dev/tail":"true"},"name":"app-top","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"role":"app-top"}},"strategy":{"rollingUpdate":{"maxSurge":2,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app.kubernetes.io/managed-by":"skaffold-v0.35.0","role":"app-top","skaffold.dev/builder":"google-cloud-build","skaffold.dev/cleanup":"true","skaffold.dev/deployer":"kustomize","skaffold.dev/tag-policy":"envTemplateTagger","skaffold.dev/tail":"true"}},"spec":{"containers":[{"image":"gcr.io/kube-sandbox-181504/app-top:3b336e6","imagePullPolicy":"Always","name":"app-top","ports":[{"containerPort":5000,"name":"app","protocol":"TCP"}]},{"image":"gcr.io/kube-sandbox-181504/auto-ssl:master","imagePullPolicy":"Always","name":"nginx","ports":[{"containerPort":80,"name":"http","protocol":"TCP"},{"containerPort":443,"name":"https","protocol":"TCP"}],"resources":{"limits":{"cpu":"250m","memory":"275Mi"},"requests":{"cpu":"100m","memory":"90Mi"}},"volumeMounts":[{"mountPath":"/usr/local/openresty/nginx/conf","name":"nginx-config"}]}],"volumes":[{"configMap":{"name":"app-top-nginx"},"name":"nginx-config"}]}}}}
spec:
  replicas: 1
  selector:
    matchLabels:
      role: app-top
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/managed-by: skaffold-v0.35.0
        role: app-top
        skaffold.dev/builder: google-cloud-build
        skaffold.dev/cleanup: 'true'
        skaffold.dev/deployer: kustomize
        skaffold.dev/tag-policy: envTemplateTagger
        skaffold.dev/tail: 'true'
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: app-top-nginx
            defaultMode: 420
      containers:
        - name: app-top
          image: 'gcr.io/kube-sandbox-181504/app-top:3b336e6'
          ports:
            - name: app
              containerPort: 5000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
        - name: nginx
          image: 'gcr.io/kube-sandbox-181504/auto-ssl:master'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 275Mi
            requests:
              cpu: 100m
              memory: 90Mi
          volumeMounts:
            - name: nginx-config
              mountPath: /usr/local/openresty/nginx/conf
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 2147483647
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2019-08-14T04:32:20Z'
      lastTransitionTime: '2019-08-14T04:32:20Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
