---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - deploy.yaml
  - svc.yaml
  - nginx-configmap.yaml
images:
  - name: yamlamadindong
    newName: yamlamadingdong
    newTag: latest
  - name: auto-ssl
    newName: gcr.io/kube-sandbox-181504/auto-ssl
    newTag: master
